# Lista paczkomatów w Zielonej Górze
PACZKOMATY_ZGO = [
    {"kod": "ZGO02L", "ulica": "ul. Konstytucji 3 Maja 23"},
    {"kod": "ZGO19M", "ulica": "ul.Dworcowa 27"},
    {"kod": "ZGO09M", "ulica": "ul. Staszica 5"},
    {"kod": "ZGO36M", "ulica": "ul. Łużycka 18"},
    {"kod": "ZGO03N", "ulica": "ul. Wyszyńskiego 22A"},
    {"kod": "ZGO01APP", "ulica": "ul. Zawadzkiego \"Zośki\" 14"},
    {"kod": "ZGO08A", "ulica": "ul. Kożuchowska 10"},
    {"kod": "ZGO77M", "ulica": "ul. Harcerska 9"},
    {"kod": "ZGO04M", "ulica": "ul. Urszuli 1"},
    {"kod": "ZGO11N", "ulica": "ul. Truskawkowa 1B"},
    {"kod": "ZGO14M", "ulica": "ul. Głogowska 85"},
    {"kod": "ZGO67M", "ulica": "ul. osiedle Kaszubskie 3"},
    {"kod": "ZGO07A", "ulica": "ul. Pionierów Lubuskich 72"},
    {"kod": "ZGO15M", "ulica": "ul. Nowy Kisielin - Odrzańska 51a"},
    {"kod": "ZGO52M", "ulica": "ul. Jędrzychowska 46"},
    {"kod": "ZGO13N", "ulica": "ul. Kożuchowska 30"},
    {"kod": "ZGO24M", "ulica": "ul. Turystyczna 1 A"},
    {"kod": "ZGO82M", "ulica": "ul. Geologów 2"},
    {"kod": "ZGO07BAPP", "ulica": "ul. Batorego 118 C"},
    {"kod": "ZGO07M", "ulica": "ul. Aleja Zjednoczenia 118"},
    {"kod": "ZGO04N", "ulica": "ul. Stefana Batorego 81"},
    {"kod": "ZGO41M", "ulica": "ul. Lwowska 2"},
    {"kod": "ZGO40M", "ulica": "ul. Lisia 63"},
    {"kod": "ZGO04L", "ulica": "ul. Wojska Polskiego 106"},
    {"kod": "ZGO01H", "ulica": "ul. Agrestowa 5A/11"},
    {"kod": "ZGO66M", "ulica": "ul. Konicza 34"}
]