def calculateTime(edge):
    effectiveSpeed = edge["predkoscSrednia"] * edge["natezenieRuchu"]
    return round(edge["km"] / effectiveSpeed * 60, 1)




points = [
    {
        "id": "ZG",
        "name": "Zielona Góra",
        "lat": 51.9354800,
        "lon": 15.5064300
    },
    {
        "id": "NB",
        "name": "Nowogród Bobrzański",
        "lat": 51.798346,
        "lon": 15.236140
    },
    {
        "id": "ZR",
        "name": "Żary",
        "lat": 51.636,
        "lon": 15.138
    },
    {
        "id": "ZA",
        "name": "Żagań",
        "lat": 51.616591,
        "lon": 15.317660
    },
    {
        "id": "SZP",
        "name": "Szprotawa",
        "lat": 51.567,
        "lon": 15.538
    },
    {
        "id": "KOZ",
        "name": "Kożuchów",
        "lat": 51.745,
        "lon": 15.595
    },
    {
        "id": "NS",
        "name": "Nowa Sól",
        "lat": 51.8011,
        "lon": 15.7075
    }
]


edges = [
    # ZG
    {
        "from": "ZG",
        "to": "ZR",
        "km": 44.90,
        "droga": "DK27",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 4,
    },
    {
        "from": "ZG",
        "to": "ZR",
        "km": 48.70,
        "droga": "DK32 + DK27",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 4,
    },
    {
        "from": "ZG",
        "to": "ZA",
        "km": 46.20,
        "droga": "DK27 + DW295",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 3,
    },
    {
        "from": "ZG",
        "to": "ZA",
        "km": 58.20,
        "droga": "S3 + DW296",
        "predkoscMax": 120,
        "predkoscSrednia": 87,
        "natezenieRuchu": 0.80,
        "jakoscDrogi": 4,
    },
    {
        "from": "ZG",
        "to": "SZP",
        "km": 53.60,
        "droga": "S3 + DW297",
        "predkoscMax": 120,
        "predkoscSrednia": 87,
        "natezenieRuchu": 0.80,
        "jakoscDrogi": 4,
    },
    {
        "from": "ZG",
        "to": "SZP",
        "km": 58.10,
        "droga": "S3",
        "predkoscMax": 120,
        "predkoscSrednia": 87,
        "natezenieRuchu": 0.80,
        "jakoscDrogi": 5,
    },
    {
        "from": "ZG",
        "to": "SZP",
        "km": 51.60,
        "droga": "DW283 + DW297",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.60,
        "jakoscDrogi": 3,
    },
    {
        "from": "ZG",
        "to": "KOZ",
        "km": 32,
        "droga": "S3 + DW297",
        "predkoscMax": 120,
        "predkoscSrednia": 87,
        "natezenieRuchu": 0.80,
        "jakoscDrogi": 4,
    },
    {
        "from": "ZG",
        "to": "KOZ",
        "km": 36.10,
        "droga": "S3",
        "predkoscMax": 120,
        "predkoscSrednia": 87,
        "natezenieRuchu": 0.80,
        "jakoscDrogi": 5,
    },
    {
        "from": "ZG",
        "to": "KOZ",
        "km": 28.20,
        "droga": "DW283",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.60,
        "jakoscDrogi": 3,
    },
    {
        "from": "ZG",
        "to": "NB",
        "km": 25.50,
        "droga": "DW282 + DK27",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 3,
    },
    {
        "from": "ZG",
        "to": "NS",
        "km": 26.60,
        "droga": "S3",
        "predkoscMax": 120,
        "predkoscSrednia": 87,
        "natezenieRuchu": 0.90,
        "jakoscDrogi": 5,
    },
    {
        "from": "ZG",
        "to": "NS",
        "km": 23.20,
        "droga": "S3 + Zielonogórska",
        "predkoscMax": 120,
        "predkoscSrednia": 87,
        "natezenieRuchu": 0.90,
        "jakoscDrogi": 4,
    },

    # NB
    {
        "from": "NB",
        "to": "SZP",
        "km": 40.10,
        "droga": "DW295 + DK12",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 3,
    },
    {
        "from": "NB",
        "to": "ZR",
        "km": 19.90,
        "droga": "DK27",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 4,
    },
    {
        "from": "NB",
        "to": "ZR",
        "km": 21.60,
        "droga": "DK27 + Obwodnica",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 4,
    },
    {
        "from": "NB",
        "to": "ZA",
        "km": 23.10,
        "droga": "DW295",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.60,
        "jakoscDrogi": 3,
    },
    {
        "from": "NB",
        "to": "ZA",
        "km": 33.10,
        "droga": "DK27 + DK12",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 4,
    },
    {
        "from": "NB",
        "to": "KOZ",
        "km": 31.40,
        "droga": "DW290",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.60,
        "jakoscDrogi": 3,
    },
    {
        "from": "NB",
        "to": "NS",
        "km": 39.90,
        "droga": "DW290",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.60,
        "jakoscDrogi": 3,
    },
    {
        "from": "NB",
        "to": "NS",
        "km": 54.40,
        "droga": "DK27 + S3",
        "predkoscMax": 120,
        "predkoscSrednia": 87,
        "natezenieRuchu": 0.80,
        "jakoscDrogi": 4,
    },

    # ZR
    {
        "from": "ZR",
        "to": "ZA",
        "km": 15.10,
        "droga": "DK12",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.80,
        "jakoscDrogi": 4,
    },
    {
        "from": "ZR",
        "to": "ZA",
        "km": 18.30,
        "droga": "Obwodnica + DK12",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.80,
        "jakoscDrogi": 4,
    },
    {
        "from": "ZR",
        "to": "SZP",
        "km": 32.20,
        "droga": "DK12",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 4,
    },
    {
        "from": "ZR",
        "to": "KOZ",
        "km": 40.70,
        "droga": "DK12 + DW296",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 3,
    },
    {
        "from": "ZR",
        "to": "NS",
        "km": 52.40,
        "droga": "DW296",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.60,
        "jakoscDrogi": 3,
    },

    # ZA
    {
        "from": "ZA",
        "to": "SZP",
        "km": 17.60,
        "droga": "DK12",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 4,
    },
    {
        "from": "ZA",
        "to": "KOZ",
        "km": 26.10,
        "droga": "DW296",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.60,
        "jakoscDrogi": 3,
    },
    {
        "from": "ZA",
        "to": "NS",
        "km": 37.90,
        "droga": "DW296",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.60,
        "jakoscDrogi": 3,
    },

    # SZP
    {
        "from": "SZP",
        "to": "KOZ",
        "km": 22.60,
        "droga": "DW297",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.60,
        "jakoscDrogi": 3,
    },
    {
        "from": "SZP",
        "to": "NS",
        "km": 34.30,
        "droga": "DW297",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.60,
        "jakoscDrogi": 3,
    },

    # KOZ
    {
        "from": "KOZ",
        "to": "NS",
        "km": 11.70,
        "droga": "DW297",
        "predkoscMax": 90,
        "predkoscSrednia": 65,
        "natezenieRuchu": 0.70,
        "jakoscDrogi": 3,
    },

    # lokalne rozwożenie paczek w miastach
    {
        "from": "ZG",
        "to": "ZG",
        "km": 18,
        "droga": "Lokalne rozwożenie paczek - Zielona Góra",
        "predkoscMax": 50,
        "predkoscSrednia": 36,
        "natezenieRuchu": 0.65,
        "jakoscDrogi": 4,
    },
    {
        "from": "NB",
        "to": "NB",
        "km": 8,
        "droga": "Lokalne rozwożenie paczek - Nowogród Bobrzański",
        "predkoscMax": 50,
        "predkoscSrednia": 36,
        "natezenieRuchu": 0.50,
        "jakoscDrogi": 3,
    },
    {
        "from": "ZR",
        "to": "ZR",
        "km": 13,
        "droga": "Lokalne rozwożenie paczek - Żary",
        "predkoscMax": 50,
        "predkoscSrednia": 36,
        "natezenieRuchu": 0.55,
        "jakoscDrogi": 4,
    },
    {
        "from": "ZA",
        "to": "ZA",
        "km": 11,
        "droga": "Lokalne rozwożenie paczek - Żagań",
        "predkoscMax": 50,
        "predkoscSrednia": 36,
        "natezenieRuchu": 0.55,
        "jakoscDrogi": 4,
    },
    {
        "from": "SZP",
        "to": "SZP",
        "km": 9,
        "droga": "Lokalne rozwożenie paczek - Szprotawa",
        "predkoscMax": 50,
        "predkoscSrednia": 36,
        "natezenieRuchu": 0.50,
        "jakoscDrogi": 3,
    },
    {
        "from": "KOZ",
        "to": "KOZ",
        "km": 7,
        "droga": "Lokalne rozwożenie paczek - Kożuchów",
        "predkoscMax": 50,
        "predkoscSrednia": 36,
        "natezenieRuchu": 0.50,
        "jakoscDrogi": 3,
    },
    {
        "from": "NS",
        "to": "NS",
        "km": 14,
        "droga": "Lokalne rozwożenie paczek - Nowa Sól",
        "predkoscMax": 50,
        "predkoscSrednia": 36,
        "natezenieRuchu": 0.65,
        "jakoscDrogi": 4,
    },
]
for edge in edges:
    edge["czas"] = calculateTime(edge)